import os
import json
import re
import logging
from datetime import datetime
from typing import Dict, Any

from tenacity import wait_fixed, stop_after_attempt, AsyncRetrying
from fastapi_poe import get_bot_response, ProtocolMessage

from agent.state import AgentState
from agent.prompts import build_lesson_prompt, build_retry_prompt
from agent.validators import LessonContent
from config.settings import settings

# Configure logging
logging.basicConfig(level=settings.LOG_LEVEL)
logger = logging.getLogger(__name__)

async def validate_input_node(state: AgentState) -> Dict[str, Any]:
    """
    Cleans and validates the initial teaching concept.
    """
    concept = state.get("concept", "").strip()
    
    if not concept or len(concept) < 3:
        raise ValueError("Teaching concept must be at least 3 characters long.")
    
    cleaned_concept = concept.capitalize()
    
    return {
        "cleaned_concept": cleaned_concept,
        "status": "input_validated"
    }

async def generate_content_node(state: AgentState) -> Dict[str, Any]:
    """
    Calls Claude (via Poe) to generate the lesson content.
    """
    cleaned_concept = state["cleaned_concept"]
    retry_count = state.get("retry_count", 0)
    error = state.get("error")

    if retry_count > 0 and error:
        prompt = build_retry_prompt(cleaned_concept, error)
    else:
        prompt = build_lesson_prompt(cleaned_concept)

    messages = [ProtocolMessage(role="user", content=prompt)]
    
    full_response = ""
    
    logger.info(f"Generating content for: {cleaned_concept} (Attempt: {retry_count + 1})")

    async for attempt in AsyncRetrying(
        wait=wait_fixed(2),
        stop=stop_after_attempt(settings.LLM_MAX_RETRIES),
        reraise=True
    ):
        with attempt:
            try:
                full_response = ""
                async for chunk in get_bot_response(
                    messages=messages,
                    bot_name=settings.LLM_MODEL,
                    api_key=settings.POE_API_KEY
                ):
                    full_response += chunk.text
            except Exception as e:
                logger.error(f"LLM Call failed: {str(e)}")
                raise

    return {
        "structured_content": full_response,
        "status": "content_generated"
    }

async def validate_content_node(state: AgentState) -> Dict[str, Any]:
    """
    Extracts, parses, and validates the JSON content from the LLM.
    """
    raw_content = state.get("structured_content", "")
    
    # Extract JSON between curly braces if LLM included preamble
    try:
        # Look for the outermost curly braces
        json_match = re.search(r"(\{.*\})", raw_content, re.DOTALL)
        if not json_match:
            raise ValueError("No JSON object found in response.")
        
        json_str = json_match.group(1)
        
        try:
            parsed_data = json.loads(json_str)
        except json.JSONDecodeError as json_err:
            try:
                import ast
                parsed_data = ast.literal_eval(json_str)
                if not isinstance(parsed_data, dict):
                    raise ValueError("Parsed content is not a dictionary.")
            except Exception:
                raise json_err
        
        # Validate with Pydantic
        lesson_content = LessonContent(**parsed_data)
        
        return {
            "structured_content": lesson_content.model_dump(),
            "status": "content_validated",
            "error": None
        }
        
    except Exception as e:
        logger.warning(f"Validation failed: {str(e)}")
        return {
            "retry_count": state.get("retry_count", 0) + 1,
            "error": str(e),
            "status": "validation_failed"
        }

async def create_output_folder_node(state: AgentState) -> Dict[str, Any]:
    """
    Creates a timestamped directory for the lesson outputs.
    Uses a shortened version of the lesson title for the folder name.
    """
    # Prefer the catchy lesson_title generated by the LLM
    content = state.get("structured_content")
    if isinstance(content, dict) and "lesson_title" in content:
        name_source = content["lesson_title"]
    else:
        name_source = state["cleaned_concept"]
    
    # Take the first 3 words, slugify them, and add a timestamp
    words = name_source.lower().split()[:3]
    short_base = "_".join(words)
    safe_name = re.sub(r"[^a-z0-9_]+", "", short_base).strip("_")
    
    timestamp = datetime.now().strftime("%Y%m%d_%H%M")
    folder_name = f"{safe_name}_{timestamp}"
    
    base_path = os.path.expanduser(settings.OUTPUT_BASE_PATH)
    full_path = os.path.join(base_path, folder_name)
    
    os.makedirs(full_path, exist_ok=True)
    
    logger.info(f"Created output folder: {full_path}")
    
    return {
        "output_folder": full_path,
        "status": "folder_created"
    }

async def error_node(state: AgentState) -> Dict[str, Any]:
    """
    Terminal node for handling errors.
    """
    error = state.get("error", "Unknown error")
    logger.error(f"Agent failed at status {state.get('status')}: {error}")
    
    return {
        "status": "failed"
    }
